### ISSUE TITLE
Problem: Problems should be centralized

### ISSUE THREAD

**Issue by flowerornament** [TimDaub/nautilus#2]
## Problem

> morgan [2:38 PM] 
> If you want to dig into product stuff, I'd recommend checking out the Nautilus repositories and thinking about how you might be able to contribute

> John [2:38 PM] 
> which one?

Keeping ideas under individual repositories reinforces the 'decentralized' nature of the decision-making process and enables divergence (literally forks) if necessary, but since we're working toward a single protocol, divergence can lead to (1) confusion for new contributors and (2) unconscious divergence simply because the book-keeping of keeping repositories in-sync was too costly.

Meta: this issue is on `TimDaub / nautilus`, but it appplies equally to @diminator's and @msutherl's repositories.

## Proposed Solutions

1. Centralize `Nautilus` under an Ocean account / org and (at least) nominate this the official upstream fork
2. Nominate `diminator/nautilus` as the de facto upstream repo and _document it_
3. Maintain a list of all possible upstream repositories to keep in sync, maintain a manifest explaining the purpose of every branch, and document a decentralized workflow (works for repositories, but not for issues)
2. Use a collaborative document editor with a single source of truth (like Google Docs)

**Comment by TimDaub** [comment]
1. Another proposed solution (explanation on website):

http://52.59.198.28:8080/

2. @sbellem and I were discussing another solution that is quite promising. I'll document it asap.

Meta: It be cool if you could put this problem under /docs/problems/ instead of a GitHub issue such that we have it documented for eternity.

Once this problem description was committed to the repository, I'll close this issue.
